---
# Copyright 2016, Walmart Stores, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Fail if installation method is not 'distro'
  fail:
    msg: "The only supported rabbitmq_install_method for RedHat is 'distro'."
  when: rabbitmq_install_method != 'distro'

- name: Install RabbitMQ packages
  yum:
    name: "{{ rabbitmq_distro_packages }}"
    state: "{{ rabbitmq_package_state }}"
  register: install_rabbitmq
  tags:
    - rabbitmq-package-rpm
    - rabbitmq-yum-packages

# NOTE(hwoarang) on RedHat, rabbitmq-server depends on epmd.service which
# depends on epmd.socket which runs on localhost. It is just easier to let
# the rabbitmq-server launch epmd directly since we are inside a container.
- name: Add rabbitmq-server systemd service (RedHat)
  template:
    src: "rabbitmq-server.service.j2"
    dest: "/etc/systemd/system/rabbitmq-server.service"
  register: rabbitmq_server_service_added
  # NOTE(hwoarang) Normally, this task should only be executed when
  # rabbitmq_install_method == 'distro'. However, the upstream package
  # does not contain a systemd file and as such we need to provide one.
  # This should be reverted once https://github.com/rabbitmq/rabbitmq-server-release/pull/31
  # is merged and new builds of rabbitmq-server are available.
  tags:
    - rabbitmq-config

- name: Reload the systemd daemon
  systemd:
    daemon_reload: yes
  when:
    - rabbitmq_server_service_added is changed
  tags:
    - rabbitmq-config
